---
name: Perl-Critic
version: 1.097_001
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
abstract: Critique Perl source code for best-practices.
license: perl
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  Repository: http://guest@perlcritic.tigris.org/svn/perlcritic/trunk/distributions/Perl-Critic/
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
requires:
  B::Keywords: 1.05
  Carp: 0
  Config::Tiny: 2
  English: 0
  Exception::Class: 1.23
  Exporter: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Spec::Unix: 0
  File::Temp: 0
  Getopt::Long: 0
  IO::String: 0
  List::MoreUtils: 0
  List::Util: 0
  Module::Pluggable: 3.1
  PPI: 1.203
  PPI::Document: 1.203
  PPI::Document::File: 1.203
  PPI::Node: 1.203
  PPI::Token::Quote::Single: 1.203
  PPI::Token::Whitespace: 1.203
  Pod::PlainText: 0
  Pod::Select: 0
  Pod::Usage: 0
  Readonly: 1.03
  Scalar::Util: 0
  String::Format: 1.13
  base: 0
  charnames: 0
  overload: 0
  strict: 0
  version: 0
  warnings: 0
build_requires:
  Test::More: 0
  lib: 0
recommends:
  File::HomeDir: 0
  File::Which: 0
  IPC::Open2: 1
  Perl::Tidy: 0
  Pod::Spell: 1
  Readonly::XS: 0
  Regexp::Parser: 0.20
  Term::ANSIColor: 0
  Text::ParseWords: 3
dynamic_config: 1
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - doc
    - tools
    - xt
  file:
    - TODO.pod
    - lib/Perl/Critic/PolicySummary.pod.PL
