# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl-Critic
version:      0.09
version_from: lib/Perl/Critic.pm
installdirs:  site
requires:
    Config::Tiny:                  2
    File::Spec:                    0
    List::MoreUtils:               0
    List::Util:                    0
    Pod::Usage:                    0
    PPI:                           1.101
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
