## name lvalue
## failures 1
## cut

substr( $foo, 2, 1 ) = 'XYZ';

#-----------------------------------------------------------------------------

## name 4 arg substr
## failures 0
## cut

substr $foo, 2, 1, 'XYZ';

#-----------------------------------------------------------------------------

## name rvalue
## failures 0
## cut

$bar = substr( $foo, 2, 1 );

#-----------------------------------------------------------------------------

## name hash rvalue
## failures 0
## cut

%bar = ( foobar => substr( $foo, 2, 1 ) );

#-----------------------------------------------------------------------------

## name substr as word
## failures 0
## cut

$foo{substr};

#-----------------------------------------------------------------------------

## name low precedence boolean blocks assignment
## failures 0
## cut

'x' eq substr $foo, 0, 1 or $foo = 'x' . $foo;

#-----------------------------------------------------------------------------

##############################################################################
#      $URL: http://perlcritic.tigris.org/svn/perlcritic/branches/Perl-Critic-1.111/t/BuiltinFunctions/ProhibitLvalueSubstr.run $
#     $Date: 2010-05-22 17:48:12 -0500 (Sat, 22 May 2010) $
#   $Author: wyant $
# $Revision: 3816 $
##############################################################################

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab shiftround :
